---
title: "In the Spotlight"
output: 
  html_document:
    toc: FALSE
    css: css/indexstyle.css
---

### Currently exploring...
:::{.question-box}
  How can we minimize energy consumption in wearable devices without compromising functionality?
:::

::: {.p}
I am developing innovative, energy-efficient data management techniques for wearables, including adaptive sensing, application-aware sensing, domain-specific summarization, and lazy data transmission.
:::

:::{.p}
My research aims to significantly extend the battery life of wearable devices while maintaining high accuracy for inference models. This has far-reaching implications for various applications, from revolutionizing healthcare through continuous patient monitoring to enhancing athletic performance and enabling scientific exploration in remote environments.  By reducing our reliance on external power sources, we can increase accessibility to wearable technology, particularly in austere or limited-access environments like military missions, cargo ships, wildlife migration, and even in-body implants. Furthermore, extending the lifespan of wearables contributes to a more sustainable future by reducing electronic waste. Ultimately, my goal is to unlock the full potential of wearables for enhancing human capabilities and well-being while minimizing their environmental impact.
:::

### Latest news

### Recent work

### Expanding my knowledge

### Current initiatives
